# Configurazione SwiftLint per TakeASip

# Regole disabilitate
disabled_rules:
  - trailing_whitespace
  - todo
  - force_cast
  - line_length
  - identifier_name

# Regole configurate
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - prohibited_super_call
  - fatal_error_message
  
# Configurazioni personalizzate
line_length:
  warning: 120
  error: 200
  
file_length:
  warning: 400
  error: 1000
  
# Paths da ignorare
excluded:
  - Pods
  - build
  - release
